poetry.lock, pyproject.toml, reaper/cogs/auto_response.py, reaper/cogs/global_replies.py, reaper/cogs/image_response.py, reaper/cogs/log_reading.py, reaper/cogs/mod_search.py, reaper/cogs/playtester_ping.py, reaper/main.py, reaper/util/master_status.py
Replaces all `prints` with a logger in order to have more usable logs when running the bot.
Closes #5
=> feat: Replace cases of prints with logger

reaper/main.py
=> fix: Create data JSON files if they don't exist

reaper/cogs/playtester_ping_proxy.py
=> feat: Log playtester proxy pings

.github/workflows/format-check.yml, reaper/main.py
Run format check on push and pull requests using `black` as the formatter
Closes #7
=> ci: Run format check on push and pull requests

reaper/cogs/log_reading.py, reaper/cogs/ticket_auto_response.py, reaper/main.py
Move responding to tickets to own cog to further modularise the bot
=> refactor: Move responding to tickets to own cog

.github/dependabot.yml
=> feat: Add dependabot config file

.vscode/settings.json
=> build: Add vscode settings to format on save

reaper/cogs/log_reading.py
**Needs testing!!!**
This PR is mostly addressing readability and therefore does not change any actual functionality. I plan to return to this cog to refactor/improve it further. The code is heavily reworked to avoid possible issues that could occur when this code is being run.
Major changes:
- Instead of writing to the same file, BytesIO is now used to avoid possible conflicts
- All global variables have been reworked to be local to avoid possible conflicts
- Unused code/code that doesn't seem to do anything has been removed -> 751cc47257b8371dea6a1f30a2557262631864e2
- Changed nested ifs to guards to improve readability -> 54d736a5b319e6821e11439c7c5b2cc88bd213b6
- All variables and functions have been changed to snake_case -> 5ae09c6742d6e9241caca20d1312f35abf891069
- Removed a random …
=> refactor: Improve log reading cog readability

reaper/cogs/auto_react_reports.py
Remove cooldown check from `auto_react_reports` cog as an adjustable cooldown is not necessary in this case
=> feat: Remove cooldown check from auto_react_reports cog

reaper/cogs/image_response.py
=> feat: Handle screenshots showing ERROR_DEVICE_HUNG

reaper/cogs/image_response.py
Handle FlightCore error message in regards to default install path when it comes to EA App
Closes #55
=> feat: Handle FlightCore error message in regards to default install path

reaper/cogs/image_response.py
Add handling for the Tauri IPC error message notification in FlightCore to image reader
=> feat: Handle Tauri IPC error message

example.config.toml, reaper/cogs/log_reading.py
Forgive me for the variable names lol
=> feat: Make log reader post links to logs to channel

reaper/cogs/auto_response.py
Also listen for `1st` for auto-response for first person embark animation
Previously wouldn't catch a sentence like
> how do u get that mod where its like 1st person embark and executions?
=> feat: Also listen for `1st` for auto-response

reaper/cogs/auto_react_reports.py
=> feat: Add report format reminder

reaper/cogs/log_reading.py
Adds an auto response for `NSGetModDownloadLinkByModName`. Note that i didn't test this
=> feat: Add `NSGetModDownloadLinkByModName` auto-response

reaper/cogs/doc_search.py, reaper/main.py
Pretty basic, not much to say
Closes #95
=> feat: Add docs search command

reaper/cogs/allowed_users.py, reaper/cogs/auto_react_reports.py, reaper/cogs/auto_response.py, reaper/cogs/doc_search.py, reaper/cogs/global_replies.py, reaper/cogs/image_response.py, reaper/cogs/log_reading.py, reaper/cogs/master_check.py, reaper/cogs/mod_search.py, reaper/cogs/playtester_ping_proxy.py, reaper/cogs/playtester_ping_release_candidate.py, reaper/cogs/price_check.py, reaper/cogs/rules_writer.py, reaper/cogs/sentiment_analyzer.py, reaper/cogs/ticket_auto_response.py, reaper/cogs/user_replies.py, reaper/main.py, reaper/util/json_handler.py, reaper/util/master_status.py
Just reorders and groups dependencies using [isort](https://pypi.org/project/isort/).
=> style: Sort dependency imports with isort

reaper/cogs/image_response.py
`then` -> `the`
`NanohmProtogen` -> `NachosChipeados`
=> fix: Fix typo + update vanillaplus link

pyproject.toml, reaper/__init__.py, reaper/cogs/__init__.py, reaper/util/__init__.py
Require that all public packages have an `__init__.py` and add said files.
=> fix: Add missing `__init__.py`
