R2NorthstarTools/Reaper

reaper/cogs/auto_response.py
reaper/cogs/global_replies.py
reaper/cogs/image_response.py
reaper/cogs/log_reading.py
reaper/cogs/mod_search.py
reaper/cogs/playtester_ping.py
reaper/util/master_status.py

For some reason the logging configuration is not inherited. This approach is ugly but works for now.

fix: Define logging configuration in every source file

---

example.config.toml
poetry.lock
pyproject.toml
reaper/cogs/sentiment_analyzer.py
reaper/main.py

Should take care of #13 
**Please double check the poetry related files, I've never used it before and it was a fight to get it working.**
How it works:
The bot will cache sentiments of recent messages and warn moderators in a channel if it negative sentiments outweigh positive and neutral sentiments. I tested the performance checking each message on a Hetzner CPX21 server (which was also running two game servers at the time) and it seems like checking every message is feasible. You can specify how many messages are checked and how many messages are cached if the results or performance aren't satisfactory. I decided to not have it ping moderators as it might get spammy.
Performance demo:

feat: Sentiment Analyzer

---

reaper/cogs/auto_react_reports.py
reaper/cogs/auto_response.py
reaper/main.py

In order to further modularise the bot and clean up the `auto_response` cog
Part of refactoring the codebase

refactor: Move reports reactions to own cog

---

example.config.toml
reaper/cogs/playtester_ping_proxy.py

Check channel before proxy pinging playtesters to only allow specific channels to prevent (accidentally) pinging playtesters in irrelevant channels.

feat: Check channel before proxy pinging playtesters

---

reaper/cogs/image_response.py

Right now just tells the message author to send full logs
Example image:

feat: Handle screenshot showing "Engine Error"

---

reaper/cogs/rules_writer.py

Discord has a 2000 character limit for messages. Our rules are more than that. To make it easier to delete the previous version it makes sense to split it into larger chunks than a message per line. This code is pretty dirty but does the trick.

feat: Split rules into larger messages

---

.vscode/settings.json

Adds vscode settings entry for the flake8 extension which errors and warnings to ignore
Taken from #36

build: Set vscode settings flake8 args

---

.vscode/settings.json

Add vscode setting for paths to look at for imports as otherwise it seems to fail to detect some of the libraries that are part of the project
Without this change:

build: Add vscode setting for paths to look at for imports

---

reaper/cogs/playtester_ping_proxy.py

by sending message in dedicated channel as opposed to in context to command
Closes #41

fix: Resolve playtester proxy ping not triggering notification

---

reaper/cogs/playtester_ping_proxy.py

Create thread on playtester proxy ping by requiring an extra arg that contains the name of the thread

feat: Create thread on playtester proxy ping

---

reaper/cogs/playtester_ping_release_candidate.py

Delay release-candidate playtester ping message as Thunderstore CDN cache takes a while to invalidate and as such any client pulling from the API will still see the old version when pulling too early.
This is a very barebones implementation that just waits 30 minutes but does the trick. A better approach would be to poll API every X minutes until the CDN refreshed.

feat: Delay release-candidate playtester ping message

---

reaper/cogs/image_response.py

Detects mention of `TCP` and `8081`  and if both match drops a message regarding forwarding TCP ports not being necessary for Northstar.

feat: Add a case for handling screenshots showcasing TCP forwarding

---

reaper/cogs/log_reading.py

Send a message if no issues where found in the log as opposed to not responding at all
Potentially we should only do this in ticket channel as to not spam other enabled channels like `#northstar-chat` as well
Related to #48

feat: Send a message if no issues where found in the log

---

reaper/cogs/log_reading.py

Closes #9.
Adds a check for `Invalid Value` which really should just be a message about failed port forwarding instead but Cloudflare appears to be interfering with it. See https://github.com/R2Northstar/Northstar/issues/685 for more info
~~Also some minor nitpicking, changes repeated if statements to elif.~~ --> 1d8b0744939b76f15e6183584e361f084ad11326

feat: Add invalid value case for log reader

---

reaper/cogs/auto_response.py

feat: Add auto-response for first person animations in Northstar

---

.github/workflows/ruff.yml
.vscode/settings.json
reaper/cogs/install_channel_embed.py

Ruff is a new supported python linter. Since the flake8 action has an expire date I figured it would be good to add Ruff as a solution.
Pros:
- Ruff keeps things pythonic and readable
- Ruff does a lot of the same things flake8 does
- Ruff does not require anything to annotate PRs and commits and instead does it out of the box
- Ruff is a lot faster than flake8

ci: Add ruff linter action

---

reaper/cogs/rules_writer.py

Update URL to grab rule changes from as the documentation which also contained the rules has been moved to a new repo https://github.com/R2Northstar/NorthstarDocs

fix: Update URL to grab rule changes from

---

reaper/cogs/auto_response.py
reaper/cogs/image_response.py
reaper/cogs/install_channel_embed.py

from GitBook to MkDocs
Closes #63

fix: Update links to point to new wiki

---

.github/workflows/format-check.yml

ideally we swap back to the master branch when the action is fixed

ci: Use tagged version of black linting action

---

reaper/cogs/log_reading.py

Closes #56
Closes #58 
You're just gonna have to trust me on a lot of the regex for this. Please see the TODO's left in comments.
I tested this code with several random logs, and in each log this new version's reply was better or equal to the old version.
Functionality changes:
- Added compile error print out
- Fixed cases where the bot would not respond with any useful information
- Removed the full print out for script errors
- My reasoning for this is due to the bot using embeds, the script output is hard to read and generally not useful to the user. I have replaced it with just the error, and added possible fixes. The humans helping the user would open the log anyways.
- Did not include double barrel crash
- This error seems extremely rare/not happening anymore
- Changed mod print out …

refactor: Log Reader Rewrite

---

reaper/cogs/log_reading.py

1 line change, not much to say
This feature already existed but I guess how dev logs are marked within logs got changed?

fix: Prevent reaper from replying to dev logs

---

reaper/cogs/log_reading.py

- Fixed linking to the wrong mod
- Added link to a compatibility patch that fixes the issues when having Hud Revamp and Client Kill Callback enabled at the same time

fix: Update Client Kill Callback auto-response

---

reaper/cogs/log_reading.py

fix: Typo in compile error search

---

pyproject.toml
reaper/cogs/auto_response.py
reaper/cogs/mod_search.py
reaper/cogs/playtester_ping_release_candidate.py
reaper/util/master_status.py

`logging.warn` is deprecated in favour of `logging.warning`
See [`G010`](https://docs.astral.sh/ruff/rules/logging-warn/)

fix: Use `logger.warning` instead of `logger.warn`
